// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATYdQ73S1jUR3Y_iuh85NZ3pSq_cpW_2w',
    appId: '1:751325598222:web:62201c6771f288d712a25f',
    messagingSenderId: '751325598222',
    projectId: 'lifeguard-finance-f09c1',
    authDomain: 'lifeguard-finance-f09c1.firebaseapp.com',
    storageBucket: 'lifeguard-finance-f09c1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE2urOJsZwk4hYo-EDex14grgKFArxI5U',
    appId: '1:751325598222:android:e3fe7ac6a95ab8f912a25f',
    messagingSenderId: '751325598222',
    projectId: 'lifeguard-finance-f09c1',
    storageBucket: 'lifeguard-finance-f09c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEnX8tbQgaf-RFSu9Y8GSvMHSDORhOBqA',
    appId: '1:751325598222:ios:855f2a257af856b712a25f',
    messagingSenderId: '751325598222',
    projectId: 'lifeguard-finance-f09c1',
    storageBucket: 'lifeguard-finance-f09c1.firebasestorage.app',
    iosBundleId: 'com.lifeguard.lifeguardFinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEnX8tbQgaf-RFSu9Y8GSvMHSDORhOBqA',
    appId: '1:751325598222:ios:855f2a257af856b712a25f',
    messagingSenderId: '751325598222',
    projectId: 'lifeguard-finance-f09c1',
    storageBucket: 'lifeguard-finance-f09c1.firebasestorage.app',
    iosBundleId: 'com.lifeguard.lifeguardFinance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATYdQ73S1jUR3Y_iuh85NZ3pSq_cpW_2w',
    appId: '1:751325598222:web:a7906a1080c0681b12a25f',
    messagingSenderId: '751325598222',
    projectId: 'lifeguard-finance-f09c1',
    authDomain: 'lifeguard-finance-f09c1.firebaseapp.com',
    storageBucket: 'lifeguard-finance-f09c1.firebasestorage.app',
  );
}
