// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeewj6g7eZWd_g1W4WP7kiDYeItuopT4M',
    appId: '1:318069364278:web:0920f1933542ec9b64aa97',
    messagingSenderId: '318069364278',
    projectId: 'lifeguard-finance',
    authDomain: 'lifeguard-finance.firebaseapp.com',
    storageBucket: 'lifeguard-finance.firebasestorage.app',
    measurementId: 'G-MH681J71KX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7-8R4jpTsi6dFsLQn4tmZ0wRK3ru_o8c',
    appId: '1:318069364278:android:58b19491fa3aac5a64aa97',
    messagingSenderId: '318069364278',
    projectId: 'lifeguard-finance',
    storageBucket: 'lifeguard-finance.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH--1INdV7TpeG1p4jNGY8cjKmn-7flqs',
    appId: '1:318069364278:ios:3ae034b58e10d1d964aa97',
    messagingSenderId: '318069364278',
    projectId: 'lifeguard-finance',
    storageBucket: 'lifeguard-finance.firebasestorage.app',
    iosBundleId: 'com.lifeguard.lifeguardFinance',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH--1INdV7TpeG1p4jNGY8cjKmn-7flqs',
    appId: '1:318069364278:ios:3ae034b58e10d1d964aa97',
    messagingSenderId: '318069364278',
    projectId: 'lifeguard-finance',
    storageBucket: 'lifeguard-finance.firebasestorage.app',
    iosBundleId: 'com.lifeguard.lifeguardFinance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeewj6g7eZWd_g1W4WP7kiDYeItuopT4M',
    appId: '1:318069364278:web:d704c29cdd9dd78764aa97',
    messagingSenderId: '318069364278',
    projectId: 'lifeguard-finance',
    authDomain: 'lifeguard-finance.firebaseapp.com',
    storageBucket: 'lifeguard-finance.firebasestorage.app',
    measurementId: 'G-8E8GGPBNSQ',
  );
}
